import {Nunito} from 'next/font/google'
import Navbar from './components/navbar/Navbar'

import './globals.css'
import ClientOnly from "@/app/components/ClientOnly";
import RegisterModal from "@/app/components/modal/RegisterModal";
import ToasterProvider from "@/app/components/providers/ToasterProvider";
import LoginModal from "@/app/components/modal/LoginModal";
import getCurrentUser from "@/app/actions/gerCurrentUser";
import RentModal from "@/app/components/modal/RentModal";

export const metadata = {
    title: 'AirBnb Clone',
    description: 'Generated by create next app',
}

const font = Nunito({
    subsets: ['latin']
})

export default async function RootLayout({children,}: { children: React.ReactNode }) {
    const currentUser = await getCurrentUser()

    return (
        <html lang="en">
        <body className={font.className}>
        <ClientOnly>
            <ToasterProvider />
            <RegisterModal/>
            <LoginModal />
            <RentModal />
            <Navbar currentUser={currentUser}/>
        </ClientOnly>
        {children}
        </body>
        </html>
    )
}
