import {Nunito} from 'next/font/google'
import Navbar from './components/navbar/Navbar'

import './globals.css'
import ClientOnly from "@/app/components/ClientOnly";
import RegisterModal from "@/app/components/modal/RegisterModal";
import ToasterProvider from "@/app/components/providers/ToasterProvider";

export const metadata = {
    title: 'AirBnb Clone',
    description: 'Generated by create next app',
}

const font = Nunito({
    subsets: ['latin']
})

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={font.className}>
        <ClientOnly>
            <ToasterProvider />
            <RegisterModal/>
            <Navbar/>
        </ClientOnly>
        {children}
        </body>
        </html>
    )
}
